module.exports = {
    './src/html/CRM/member/index.html': '会员',
    './src/html/CRM/member/activeCard.html': '导购开卡目标',
    './src/html/CRM/member/member.html': '会员列表',
    './src/html/CRM/member/member_info.html': '会员详情',
    './src/html/CRM/member/filter.html': '查询条件',
    './src/html/CRM/qrcode/index.html': '二维码',
    './src/html/CRM/report/index.html': '会员数据',
    './src/html/CRM/report/index1.html': '目标管理',
    './src/html/CRM/report/index2.html': '运营指标',
    './src/html/CRM/report/index3.html': '自定义报表',
    './src/html/CRM/report/index4.html': '活动分析',
    './src/html/CRM/report/filter.html': '查询条件',
    './src/html/CRM/task/index.html': '任务分配',
    './src/html/CRM/task/group.html': '固定分组',
    './src/html/CRM/task/group2.html': '自定义分组',
    './src/html/CRM/task/new_group.html': '新建分组',
    './src/html/CRM/task/distribution.html': '任务分配',
    './src/html/CRM/task/select_group.html': '选择分组',
    './src/html/CRM/evaluate/index.html': '评价',
    './src/html/CRM/evaluate/reply_index.html': '回复评价'
}